apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-teste
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: golang-teste
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: golang-teste
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
